name: 'Aleph Web3 Hosting'
description: "Deploy a website or dApp on Aleph Cloud"
author: 'Aleph Cloud'
branding:
  icon: upload-cloud
  color: blue

inputs:
  path:
    description: "Path to the static website's files (eg frontend/out)"
    required: true
  private-key:
    description: 'The private key of the Ethereum wallet to use'
    required: false
  domain:
    description: 'Domain name to link to the deployed site (eg libertai.io)'
    required: false
    default: ''


runs:
  using: 'composite'
  steps:
    - name: Checkout my composite action repo
      uses: actions/checkout@v4
      with:
        repository: aleph-im/web3-hosting-action
        path: aleph-web3-hosting-action

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install -r ./aleph-web3-hosting-action/requirements.txt
      shell: bash

    - name: Upload on IPFS
      run: |
          result=$(python ./aleph-web3-hosting-action/publish-on-aleph.py ${{ inputs.path }})
          echo "IPFS_CID_V0=$(echo $result | jq -r '.cid_v0')" >> $GITHUB_ENV
          echo "IPFS_CID_V1=$(echo $result | jq -r '.cid_v1')" >> $GITHUB_ENV
      shell: bash


    - name: Pin with Aleph
      if: ${{ inputs.private-key != '' }}
      run: |
        mkdir --parents /home/runner/.aleph-im/private-keys
        echo ${{ inputs.private-key }} | xxd -r -p > /home/runner/.aleph-im/private-keys/ethereum.key

        pip install 'git+https://github.com/aleph-im/aleph-client@1.5.1'
        ITEM_HASH=$(aleph file pin ${{ env.IPFS_CID_V0 }} | jq -r '.item_hash')
      shell: bash


    - name: Find existing PR comment
      if: ${{ github.event_name == 'pull_request' }}
      uses: peter-evans/find-comment@v3
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: Deployed on

    - name: Comment deploy on the PR
      if: ${{ github.event_name == 'pull_request' && inputs.domain == '' }}
      uses: peter-evans/create-or-update-comment@v4
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          Deployed on:
          - https://${{ env.IPFS_CID_V1 }}.ipfs.aleph.sh

          ${{ inputs.private-key == '' && '> This link is accessible until the static files are garbage collected, pass your private key to the action to avoid this.' || '' }}
        edit-mode: replace
      continue-on-error: true

    - name: Check if private key is present for linking
      if: ${{ inputs.domain != '' && inputs.private-key == '' }}
      run: |
        echo "::error ::You must pass your private key to link the domain."
        exit 1
      shell: bash

    - name: Link domain
      if: ${{ inputs.domain != '' }}
      run: |
        echo 'y' | aleph domain attach ${{ inputs.domain }} --item-hash $ITEM_HASH
      shell: bash

    - name: Comment domain deploy on the PR
      if: ${{ inputs.domain != '' && github.event_name == 'pull_request' }}
      uses: peter-evans/create-or-update-comment@v4
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          Deployed on https://${{ inputs.domain }}
        edit-mode: replace
      continue-on-error: true
